openapi: 3.0.1
info:
  title: DMCP Avatar Gateway API
  description: API for managing DMCP Avatar Gateway operations.
  version: 1.0.0
  contact:
    name: Some Team
    email: someone@lloydsbanking.com
servers:
  - url: https://api.example.com/dmcp/avatar/v1
    description: Production server
paths:
  /:
    get:
      summary: Retrieve a list of resources.
      parameters:
        - name: limit
          in: query
          description: Maximum number of items to return
          required: false
          schema:
            type: integer
            minimum: 1
            example: 10
        - name: offset
          in: query
          description: Offset for pagination
          required: false
          schema:
            type: integer
            minimum: 0
            example: 0
      responses:
        '200':
          description: Successful response
          headers:
            ETag:
              description: Entity tag for the returned resource
              schema:
                type: string
            Last-Modified:
              description: Last modification date of the resource
              schema:
                type: string
            Access-Control-Allow-Origin:
              description: CORS header
              schema:
                type: string
            X-LBG-TXN-Correlation-Id:
              description: Transaction correlation ID
              schema:
                type: string
            X-Content-Type-Options:
              description: Content type options
              schema:
                type: string
              example: nosniff
            X-LBG-API-Version:
              description: API version header
              schema:
                type: string
          content:
            application/json; charset=UTF-8:
              schema:
                type: array
                items:
                  type: string
              example: ["resource1", "resource2"]
        '400':
          description: Bad Request
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            X-LBG-TXN-Correlation-Id:
              schema:
                type: string
            X-Content-Type-Options:
              schema:
                type: string
              example: nosniff
            X-LBG-API-Version:
              schema:
                type: string
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorData'
              example:
                errors:
                  - code: "CUS_API_ERR_400_01"
                    reasonCode: "InvalidInput"
                    message: "Bad request due to invalid input."
        # Repeat similar headers/content for other error codes below
        '401':
          description: Unauthorized
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            X-LBG-TXN-Correlation-Id:
              schema:
                type: string
            X-Content-Type-Options:
              schema:
                type: string
              example: nosniff
            X-LBG-API-Version:
              schema:
                type: string
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorData'
              example:
                errors:
                  - code: "CUS_API_ERR_401_01"
                    reasonCode: "AuthFailed"
                    message: "Authentication failed."
        '404':
          description: Not found
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            X-LBG-TXN-Correlation-Id:
              schema:
                type: string
            X-Content-Type-Options:
              schema:
                type: string
              example: nosniff
            X-LBG-API-Version:
              schema:
                type: string
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorData'
              example:
                errors:
                  - code: "CUS_API_ERR_404_01"
                    reasonCode: "NotFound"
                    message: "Resource not found."
        # Add similar blocks for 405, 406, 500, 503 as above

    head:
      summary: Retrieve headers for the list of resources.
      responses:
        '200':
          description: Successful HEAD response
          headers:
            ETag:
              schema:
                type: string
            Last-Modified:
              schema:
                type: string
            Access-Control-Allow-Origin:
              schema:
                type: string
            X-LBG-TXN-Correlation-Id:
              schema:
                type: string
            X-Content-Type-Options:
              schema:
                type: string
              example: nosniff
            X-LBG-API-Version:
              schema:
                type: string

components:
  schemas:
    error:
      type: object
      required:
        - code
        - reasonCode
        - message
      properties:
        code:
          type: string
          example: CUS_API_ERR_XXX_01
        reasonCode:
          type: string
          example: Reason Code For Error
        message:
          type: string
          example: Error Message
    errorData:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/error'